# This workflow should install niceplots and dependencies the check formatting with flake8 and black and then check the the examples run without error

name: niceplots

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8]
        numpy-version: ["1.16.6", "1.18.5"]
        mpl-version: ["3.2.*", "3.3.*"]
        include: 
          - python-version: 3.7
            blackFlag: "py37"
          - python-version: 3.8
            blackFlag: "py38"

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip wheel
        python -m pip install flake8 black 
        python -m pip install numpy==${{ matrix.numpy-version }} 
        python -m pip install matplotlib==${{ matrix.mpl-version }}
        pip install .
    - name: Lint with flake8
      if: ${{ matrix.numpy-version == 1.16.6 && matrix.mpl-version == 3.2.* }}
      run: |
        wget https://raw.githubusercontent.com/mdolab/.github/master/.flake8;
        flake8 . --count --show-source --statistics;
    - name: Lint with black
      if: ${{ matrix.numpy-version == 1.16.6 && matrix.mpl-version == 3.2.* }}
      run: |
        black . --check --diff -l 120 --target-version ${{ matrix.blackFlag }};
    - name: Test examples (this is very janky for now)
      run: |
        cd examples
        python default_formatting.py && python bar_chart_example.py && python parulaContours.py  && python plot_stacks.py
